Squash develop branch

diff --git a/tools/bin/merge-jars b/tools/bin/merge-jars
--- a/tools/bin/merge-jars
+++ b/tools/bin/merge-jars
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
-
-read -r -d '' USAGE << EOM
+read -r -d '' USAGE <<EOM
 $(basename "$0") merges two or more jars in a new one
 
 Usage:
@@ -10,7 +9,10 @@ Usage:
 EOM
 export USAGE
 
-BASE=$( cd "$(dirname "$0")" || exit; pwd )
+BASE=$(
+	cd "$(dirname "$0")" || exit
+	pwd
+)
 
 # shellcheck source=/dev/null
 source "$BASE/common.sh"
@@ -18,26 +20,25 @@ source "$BASE/common.sh"
 checkParamsAtLeast $# 3
 
 final=$(realpath "$1")
-jars=( "${@:2}" )
+jars=("${@:2}")
 
 pivot=$(mktemp -d)
 trap '{ rm -rf "$pivot"; }' EXIT
 
 list=()
 for jar in "${jars[@]}"; do
-  isValidFile "$jar"
-  list+=("$(realpath "$jar")")
+	isValidFile "$jar"
+	list+=("$(realpath "$jar")")
 done
 
-pushd > /dev/null "$pivot" || die "Error entering in temp dir"
+pushd >/dev/null "$pivot" || die "Error entering in temp dir"
 
 for jar in "${list[@]}"; do
-  echo -n "."
-  jar xf "$jar"
+	echo -n "."
+	jar xf "$jar"
 done
 
 jar cf "$final" .
 echo "done!"
 
-popd > /dev/null || die "Error returning to original dir"
-
+popd >/dev/null || die "Error returning to original dir"
diff --git a/tools/bin/prs b/tools/bin/prs
--- a/tools/bin/prs
+++ b/tools/bin/prs
@@ -3,9 +3,9 @@
 # #########################################################################
 # This script prints information about the PRs created by the authenticated user
 # in a given list of modules or the full list of git modules, eg:
-# 
+#
 # $ export GITHUB_TOKEN="...."
-# 
+#
 # $ prs  # PR for every git module relative to current working directory
 #
 # $ prs mule mule-ee mule-api # PRs only for these three modules
@@ -13,14 +13,14 @@
 # #########################################################################
 
 function die {
-  echo "$1"
-  exit 1
+	echo "$1"
+	exit 1
 }
 
 [[ -n "$GITHUB_TOKEN" ]] || die "GITHUB_TOKEN is not defined"
 
-which dw > /dev/null \
-  || die "DW not found.  Please visit https://github.com/mulesoft-labs/data-weave-native"
+which dw >/dev/null ||
+	die "DW not found.  Please visit https://github.com/mulesoft-labs/data-weave-native"
 
 # only works with mulesoft organization
 org="mulesoft"
@@ -30,21 +30,19 @@ header="Authorization: token $GITHUB_TOKEN"
 username=$(curl -s -H"$header" "https://api.github.com/user" | dw 'payload.login')
 
 if [[ $# -eq 0 ]]; then
-  modules=$(git submodule | awk '{print $2}')
+	modules=$(git submodule | awk '{print $2}')
 else
-  modules=$*
+	modules=$*
 fi
 
-for repo in $modules
-do
-  url="https://api.github.com/repos/$org/$repo/pulls?state=open&per_page=100"
-  result=$(curl -s -H"$header" "$url")
+for repo in $modules; do
+	url="https://api.github.com/repos/$org/$repo/pulls?state=open&per_page=100"
+	result=$(curl -s -H"$header" "$url")
 
-  if [[ $(echo "$result" | dw 'payload.message == "Not Found"') = "true" ]]
-  then
-    echo "$result"
-  else
-    echo "$result" | dw "payload[?($.user.login == $username)] \
+	if [[ $(echo "$result" | dw 'payload.message == "Not Found"') = "true" ]]; then
+		echo "$result"
+	else
+		echo "$result" | dw "payload[?($.user.login == $username)] \
       map ( (e) -> { \
         pr:    e.title,  \
         url:   e['_links'].html.href, \
@@ -52,5 +50,5 @@ do
         base:  e.base.repo.full_name ++ ':' ++ e.base.ref, \
         head:  e.head.repo.full_name ++ ':' ++ e.head.ref\
       })" | grep -vE "^null$"
-  fi
+	fi
 done
