Simplify the setup process (#1)
* Remove old packages and simplify configuration
* Add script to install GoLang
* Update TODOs
* Clean structure
* Add some new packages and remove old/unused ones
* Add helper scripts
* Migrate from nvm to asdf
* Add  yarn support
* Update packages

diff --git a/bin/jgrep b/bin/jgrep
--- a/bin/jgrep
+++ b/bin/jgrep
@@ -1,31 +1,32 @@
 #!/bin/bash
 
 function usage() {
-	echo "Modo de uso: $0 <patron de busqueda> | $0 -d <directorio de busqueda> <patron de busqueda>"
+	echo "Usage: "
+    echo "  $0 <pattern>"
+    echo "  $0 -d <directory> <pattern>"
 	exit 1
 }
 
 if [ $# -eq 1 ];then
 	SEARCH_DIR="."
 	PATTERN="$1"
-elif [ $# -eq 3 ]; then
-	SEARCH_DIR="$2"
-	PATTERN="$3"
+elif [ $# -eq 2 ]; then
+	SEARCH_DIR="$1"
+	PATTERN="$2"
 else
 	usage;
 fi
 
-echo "Buscando en $SEARCH_DIR/*.jar archivos con el patron: \"$PATTERN\""
+echo "Searching on $SEARCH_DIR/*.jar files containing  \"$PATTERN\""
 
-for i in $(find $SEARCH_DIR -name '*.jar')
+find "$SEARCH_DIR" -name '*.jar' -type f | while read -r i
 do
-	jar tf $i 2>/dev/null 1>&2
-	if [ $? -ne 0 ]; then
-		echo "Error leyendo archivo $i"
+	jar tf "$i" 2>/dev/null 1>&2
+	if [ ! -f "$i" ]; then 
+		echo "Error reading file $i"
 	else
-		I=$(jar tvf $i | grep $PATTERN | wc -l)
-		if [ $I -ne 0 ]; then
-			echo $i
+		if [ "$(jar tvf "$i" | grep -c "$PATTERN")" -ne 0 ]; then
+			echo "$i"
 		fi
 	fi
 done
