Improve script

diff --git a/bin/make-patch b/bin/make-patch
--- a/bin/make-patch
+++ b/bin/make-patch
@@ -6,7 +6,7 @@ $(basename "$0") creates a patch based on a list of files that have changed and
 modules where search this files.
 
 Usage:
-    $0 <modules> <files> <dest>
+    $0 <modules> <commits> <dest>
 
 Where <modules> is a file with the list of modules and <files> the list of java 
 files to include in the patch file. Finally, <dest> is a directory where will be 
@@ -21,17 +21,36 @@ BASE=$( cd "$(dirname "$0")" || exit; pwd )
 # shellcheck source=/dev/null
 source "$BASE/common.sh"
 
-checkParams $# 3
+checkParamsAtLeast $# 2
 
-modules="$1"
-files="$2"
-output="$3"
+commits=( "${@:2}" )
 
-! [[ -e $output ]] || die "$output: exists" 1
+output=$(realpath "$1")
 
-mkdir -p "$output" || die "Error creating $output" 2
+modules=$(mktemp)
+files=$(mktemp)
+pivot=$(mktemp -d)
+
+trap '{ rm "$modules";   }' EXIT
+trap '{ rm "$files";     }' EXIT
+trap '{ rm -rf "$pivot"; }' EXIT
+
+git show --format="" --name-only "${commits[@]}" \
+    | grep -v test \
+    | sed -E -e s'/^(.*)\/src\/main.*$/\1/g' \
+    | sort -u > "$modules"
+
+git show --format="" --name-only "${commits[@]}" \
+    | grep -v test \
+    | sed -E -e s'/^.*\/src\/main\/java\/(.*)\.java$/\1/g' \
+    | sort -u > "$files"
+
 
 while read -r m; do
+    if ! [[ -d "$m" ]]; then
+        continue
+    fi
+
     echo "collecting files in $m ..."
 
     cd "$m/target/classes" || die "$m/target/classes not found" 3
@@ -39,10 +58,16 @@ while read -r m; do
     while read -r f; do
         d=$(dirname "$f")
         p=$(basename "$f")
-        mkdir -p "$output/$d"
-        [[ -d "$d" ]] && find "$d" -name "$p.class" -exec cp {} "$output/$d" \;
-        [[ -d "$d" ]] && find "$d" -name "$p\$*.class" -exec cp {} "$output/$d" \;
+        mkdir -p "$pivot/$d"
+        [[ -d "$d" ]] && find "$d" -name "$p.class" -exec cp {} "$pivot/$d" \;
+        [[ -d "$d" ]] && find "$d" -name "$p\$*.class" -exec cp {} "$pivot/$d" \;
     done < "$files"
 
     cd - || exit
 done < "$modules"
+
+pushd "$pivot" || die "Error entering into pivot directory"
+
+jar cvf "$output" .
+
+popd || die "Error returning back to WD"
