Migrate asdf scripts to dotbot plugins

diff --git a/install-profile b/install-profile
--- a/install-profile
+++ b/install-profile
@@ -2,32 +2,34 @@
 
 set -e
 
-BASE_CONFIG="base"
-CONFIG_SUFFIX=".yaml"
+BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
+ENV="$BASE_DIR/install.env"
 
-META_DIR="meta"
-CONFIG_DIR="configs"
-PROFILES_DIR="profiles"
+[[ -f $ENV ]] || (echo "$ENV: not found" && exit 1)
 
-DOTBOT_DIR="dotbot"
-DOTBOT_BIN="bin/dotbot"
+# shellcheck source=/dev/null
+. "$ENV"
 
-BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+pushd "$BASE_DIR" > /dev/null
 
-
-cd "${BASE_DIR}"
-git submodule update --init --recursive --remote
-
+git -C "$BASE_DIR" submodule update --init --recursive --remote
 
 while IFS= read -r config; do
     CONFIGS+=" ${config}"
-done < "${META_DIR}/${PROFILES_DIR}/$1"
+done < "$META_DIR/$PROFILES_DIR/$1"
 
 shift
 
-
 for config in ${CONFIGS} "${@}"; do
     echo -e "\nConfigure $config"
-    configContent="$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")"
-    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c <(echo -e "$configContent")
+
+    PROFILE_CONFIG_PATH=$BASE_DIR/$META_DIR/$CONFIG_DIR/$config$CONFIG_SUFFIX
+
+    configContent="$(<"$BASE_CONFIG_PATH")\n$(<"$PROFILE_CONFIG_PATH")"
+    $DOTBOT_CMD \
+      -d "$BASE_DIR" \
+      --plugin-dir "$DOTBOT_PLUGINS/dotbot-asdf" \
+      -c <(echo -e "$configContent")
 done
+
+popd > /dev/null
